#Configurazione per il Deployment

server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;

    index index.html;

    location / {

        try_files $uri $uri/ /index.html;
    }

    location /api/{       #intercetta le richieste con /api/ e le inoltra al backend
        proxy_pass http://backend:3000;   #proxy che inoltra le richeste a backend

        
        proxy_http_version 1.1;  #per le connessioni persistenti

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;    #disattivato il bffering di nginx(manda i dati man mano che arrivano senza accumularli)
        proxy_request_buffering off; #stessa cosa perle richieste in entrata
    }

    location /socket.io/{              #intercetta le richieste con /socket.io/
        proxy_pass http://backend:3000;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;    #header per passare da http1.1 a web socket
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 86400;   #la connessione termina dopo 24 ore senza scambi di messaggi
        proxy_send_timeout 86400;

        proxy_buffering off;   
    }
}